blocknum,reason
916647,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
916647,geth failed to trace block (block=916647)
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29624b7588>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e03e9af98>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b5fdd0cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9b9c88>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9be860>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9c2940>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9c4a20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9c5d30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa731d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa78198>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab27e366a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbb58ffa20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
916647,"HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=90)"
1537984,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
1537984,geth failed to trace block (block=1537984)
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29624b7390>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e03eeff60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b5fd01be0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9904a8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9c20f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa73ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa780b8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa8d7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f954587ad30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab27e33dd8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbb57cf940>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1537984,"HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=90)"
1693765,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
1693765,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
1693765,geth failed to trace block (block=1693765)
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29624b7dd8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e03dd99e8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b5fd39160>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f973978>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f98d160>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f998ac8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9ad240>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9be208>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa906d8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbb58d2748>: Failed to establish a new connection: [Errno 111] Connection refused'))"
1693765,"HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=90)"
2632728,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
2632728,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
2632728,geth failed to trace block (block=2632728)
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29624bc438>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e03dd1a20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b5fde7f98>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f99b0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f99b240>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9a0b38>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9cd2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9f9cd470>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa76d68>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d9fa8d2e8>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbb582d7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2632728,"HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=90)"
